export const MOCK_EVENTS = [
  {
    id: "1",
    title: "NexGen Tech Summit 2026",
    description: "Experience the latest in AI, Quantum Computing, and Neural Interfaces with global industry leaders. This summit brings together the brightest minds to discuss the future of humanity in the digital age.",
    longDescription: "NexGen Tech Summit is the premier event for technology enthusiasts and professionals. In 2026, we focus on the intersection of Artificial Intelligence and biology. Join us for keynote speakers from OpenAI, Neuralink, and Google DeepMind, hands-on workshops with next-gen hardware, and networking sessions that will define your career.",
    date: "May 15, 2026",
    time: "09:00 AM - 06:00 PM",
    venue: "Innovation Hub & Convention Center",
    location: "San Francisco, CA",
    category: "Technology",
    price: "199",
    attendees: 1200,
    organizer: "TechGlobal Events",
    image: "https://images.unsplash.com/photo-1540575861501-7ad05823c9f5?q=80&w=2070",
  },
  {
    id: "2",
    title: "Midnight Symphony: Neon Nights",
    description: "An immersive audio-visual journey featuring world-class electronic artists and holographic art installations.",
    longDescription: "Step into the future of nightlife. Midnight Symphony returns to Berlin with a more ambitious lineup than ever before. Featuring 360-degree spatial audio, local and international techno icons, and an interactive light show controlled by the crowd's energy. This isn't just a concert; it's a sensory evolution.",
    date: "June 02, 2026",
    time: "10:00 PM - 06:00 AM",
    venue: "Echo Dome",
    location: "Berlin, DE",
    category: "Music",
    price: "85",
    attendees: 5000,
    organizer: "MSX Productions",
    image: "https://images.unsplash.com/photo-1470225620780-dba8ba36b745?q=80&w=2070",
  },
  {
    id: "3",
    title: "Creative Canvas Workshop",
    description: "Unleash your creativity in this hands-on masterclass led by renowned digital artists. Perfect for all skill levels.",
    longDescription: "Ever wanted to master digital painting but didn't know where to start? Our Creative Canvas Workshop provides Wacom tablets, professional software, and expert guidance. Spend a day learning techniques used by concept artists at Pixar and Marvel. You'll leave with your own completed masterpiece.",
    date: "May 20, 2026",
    time: "11:00 AM - 04:00 PM",
    venue: "The Palette Loft",
    location: "New York, NY",
    category: "Arts",
    price: "0",
    attendees: 45,
    organizer: "Artistry Collective",
    image: "https://images.unsplash.com/photo-1513364776144-60967b0f800f?q=80&w=2071",
  },
  {
    id: "4",
    title: "Global Business Gala",
    description: "Networking at the highest level. Connect with CEOs and pioneers in global strategy and finance.",
    longDescription: "The Global Business Gala is an invite-only event that we're opening up to a select few this year. Set against the backdrop of the stunning Dubai skyline, this evening includes a keynote on global market shifts, a 7-course dinner, and high-stakes networking opportunities that transcend borders.",
    date: "July 12, 2026",
    time: "07:00 PM - 11:30 PM",
    venue: "Skyline Lounge (Burj Heights)",
    location: "Dubai, UAE",
    category: "Business",
    price: "450",
    attendees: 300,
    organizer: "Prime Strategy Group",
    image: "https://images.unsplash.com/photo-1511578314322-379afb476865?q=80&w=2069",
  },
  {
    id: "5",
    title: "Cyber Security Hackathon",
    description: "48 hours of intense coding. Protect the grid and win massive bounty rewards in a competitive environment.",
    longDescription: "Calling all white-hat hackers. The grid is under simulated attack. Your team has 48 hours to identify vulnerabilities, patch the code, and counter-attack the simulation. With $50,000 in bounties on the line, this is the ultimate test of your security knowledge and speed.",
    date: "May 28, 2026",
    time: "48 Hours (Continuous)",
    venue: "Underground Labs (Secret Location)",
    location: "London, UK",
    category: "Technology",
    price: "25",
    attendees: 150,
    organizer: "CyberSafe Initiative",
    image: "https://images.unsplash.com/photo-1550751827-4bd374c3f58b?q=80&w=2070",
  },
  {
    id: "6",
    title: "Indie Film Festival",
    description: "Premiere screenings of the year's most provocative independent cinema masterpieces and director Q&As.",
    longDescription: "Experience cinema in its purest form. Our festival showcases 20 films from upcoming directors across the globe. From gritty documentaries to surrealist fantasies, these are stories that wouldn't find a home in a traditional multiplex. Includes a red-carpet opening and nightly networking drinks.",
    date: "August 05, 2026",
    time: "04:00 PM - 11:00 PM",
    venue: "Ciné Park & Art House",
    location: "Paris, FR",
    category: "Arts",
    price: "35",
    attendees: 800,
    organizer: "Nouvelle Vague Cinema",
    image: "https://images.unsplash.com/photo-1485846234645-a62644f84728?q=80&w=2059",
  },
];
